In [ ]:
print("Hello") # this is a comment line

In [ ]:
'''This is a multiline comment
block
''' 

In [ ]:
'''
hi i am
navanil'''

In [ ]:
i = 1

In [ ]:
for i in range(0,10):
    print (i)
    

In [ ]:
print("Hello")
print("World");

In [ ]:
print("Hello " * 5)
print("World")

In [ ]:
a = int(input("Enter a no:"))

In [ ]:
print(a)

In [ ]:
emp_name = input("Enter a name:")
emp_surname = input("Enter surname name")
print("The employee name is ",\
      emp_name+ " " +\
      emp_surname)


In [ ]:
a = 10
b = 40

In [ ]:
print(a,b)

In [ ]:
c = 100
d = 85

In [ ]:
print(c,d)

In [ ]:
a = int(input("Enter the first number -->"))
b = int(input("Enter second number -->"))
sum = a + b
print(sum)

In [ ]:
a = input("Enter the first number -->")
b = input("Enter second number -->")
sum = int(a) + int(b)
print(sum)

In [ ]:
a = int(input("Enter the first number -->"))
b = int(input("Enter second number -->"))
sum = a + b
print("Num1 = ",a,",Num2 = ",b,"and Total = ",sum)

In [ ]:
a = int(input("Enter the first number -->"))
b = int(input("Enter second number -->"))
sum = a + b
print("Sum of {} and {} is {}".format(a,b,sum))
print("Sum of %d and %d is %d"%(a,b,sum))
print("Sum of {0} and {1} is {2}".format(a,b,sum))
print("Sum of {2} and {1} is {0}".format(sum,b,a))
print("Sum of {x} and {y} is {z}".format(x=a,y=b,z=sum))

In [ ]:
x = 100
y = 200

In [ ]:
print(x,y)

In [ ]:
x = 500
y = 500

In [ ]:
a = 101
b = 50
print("a+b=",a+b)
print("a-b=",a-b)
print("a*b=",a*b)
print("a/b=",a/b)
print("a//b=",a//b)
print("a%b=",a%b)
print("a**b=",a**b)

In [ ]:
num1 = int(input("Enter the first number -->"))
num2 = int(input("Enter second number -->"))
if (num1 > num2):
     print("The first number is maximum...")
     print(num1)
elif(num1 < num2):
    print("The second number is maximum...")
    print(num2)
else:
    print("Both are same")
    print(num1,num2)
print("End of program")
    

In [ ]:
#take two integers from keyboard as input display menu
'''-> Addition
-> Substraction
-> Multiplication
->Division
-> Remainder
integer division
exponentiation
exit
'''

In [ ]:
print("1.Addition")
print("2.Subtraction")
print("3.Multiplication")
print("4.Division")
print("5.Remainder")
print("6.Integer Division")
print("7.Exponentiation")
print("0.Exit")

In [ ]:
var = 1
while(var == 1):

    a = int(input("Enter the first number -->"))
    b = int(input("Enter second number -->"))
    print("1.Addition")
    print("2.Subtraction")
    print("3.Multiplication")
    print("4.Division")
    print("5.Remainder")
    print("6.Integer Division")
    print("7.Exponentiation")
    print("0.Exit")
    ch = int(input("Enter choice"))
    if(ch == 1):
        print("Sum of",a,"and",b,"is",a+b)
    elif(ch == 2):
        print("Subtration of",a,"and",b,"is",a-b)
    elif(ch == 3):
        print("Multiplication of",a,"and",b,"is",a*b)
    elif(ch == 4):
        if(b != 0):
            print("Division of",a,"and",b,"is",a/b)
        else:
            print("Wrong input")
    elif(ch == 5):
        if(b != 0):
            print("Remainder of",a,"and",b,"is",a%b)
        else:
            print("Wrong input")

    elif(ch == 6):
        if(b != 0):
            print("Integer division of",a,"and",b,"is",a//b)
        else:
            print("Wrong Input")
    elif(ch == 7):
        print("Exponentiation of",a,"and",b,"is",a**b)
    elif(ch == 0):
        break;
    else:
        print("Wrong choice")

In [ ]:
#LOOPING 2ND CLASS 

In [ ]:
i = 1
while(i <= 5):
    print("Executing for i = {}".format(i))
    i+=1
print("End of the program...")

In [ ]:
i = 1
while(i <= 5):
    print("India "*i)
    i+=1


In [ ]:
n = int(input("Enter the no of lines:"))
i = 1
while(i <= n):
    print(" "*(n-i),end="")
    print("*"*(2*i - 1),end = "")
    print("")
    i+=1


In [ ]:
n = int(input("Enter the no of lines:"))
i = n
while(i>=1):
    print(" "*(n-i),end="")
    print("*"*(2*i - 1),end="")
    print("")
    i-=1

i = 2
while(i <= n):
    print(" "*(n-i),end="")
    print("*"*(2*i - 1),end = "")
    print("")
    i+=1
    
    

In [ ]:
n = 0
while(n%2 == 0):
    n = int(input("Enter the no of lines:"))

m = (n+1)/2
m = int(m)
i = 1
while(i<=n):
    if(i > m):
        b = n-i
        s = 2*(i-m) + 1
    else:
        b = i - 1
        s = 2*(m-i) + 1
    print(" "*b,end="")
    print("*"*s,end="")
    print("")
    i+=1
            

            
    


In [ ]:
for i in [11,22,33,44,55,66]:
    print("i=",i)

In [ ]:
for i in range(0,5):
    print("i =",i)

In [ ]:
for i in range(0,5,2):
    print("i = {}".format(i))
print("#######")
print(i)

In [ ]:
for i in range(5,1,-2):
    print("i =",i)
    

In [ ]:
n = 0
while(n%2 == 0):
    n = int(input("Enter the no of lines:"))

m = (n+1)/2
m = int(m)
i = 1
for i in range(1,n+1):
    if(i > m):
        b = n-i
        s = 2*(i-m) + 1
    else:
        b = i - 1
        s = 2*(m-i) + 1
    print(" "*b,end="")
    print("*"*s,end="")
    print("")
    
            

            
    


In [ ]:
#Magic no
n = int(input("Enter the number:"))
t = n
while(t>9):
    print("Doing again...")
    s = 0
    while(t != 0):
        d = t%10
        t = t//10
        s = s + d
    t = s
print("Output = ",t)


In [ ]:
# sum = 1+2+3+4+10+5+6+7+8+28+9....... n terms
n = int(input("Enter the no of terms:"))
s=0
m_s = 0
c=0
term = 1
for i in range(1,n+1):
    if(i%5 != 0): 
        s = s + term
        m_s = m_s + term
        print("if-m_s ",m_s)
        term = term + 1
        print("if-s ",s)
    else:
        s = s + m_s
        print("els-s ",s)
        print("els-m_s ",m_s)
        m_s = 0

print("Sum = ",s)
   




In [ ]:
n = int(input("Enter the no of terms:"))
fsum = tsum = 0
term =1
for i in range(1,n+1):
    if(i%5 ==0 ):
        fsum += tsum
        print("Adding tsum --> ",tsum)
        tsum = 0
    else:
        fsum += term
        print("Adding term --> ",term)
        tsum+= term
        term+= 1
    
print(fsum)

In [ ]:
#STRINGS

In [ ]:
my_str = "university"
print(my_str)
print(my_str[-5:-8:-1])
print(my_str[::-1])
print(my_str[4:8])
print(my_str[9:5:-2])
print(my_str[-7:6:3])

In [ ]:
import math 
a = 4.6
print(math.ceil(a))
print(math.floor(a))
b = 9
print(math.sqrt(b))
print(math.exp(3.0))
print(math.log(2.0))
print(math.pow(2.0,3.0))
print(math.sin(0))
print(math.cos(0))
print(math.tan(45))
print(abs(-4.5))


In [ ]:
mysqrt = math.sqrt  #only in py3.7
print(mysqrt(16))

In [ ]:
my_str = "   caLCuttA uNIvErsity"
print(my_str)
print(my_str.capitalize())
print(my_str.upper())
print(my_str.lower())
print(my_str.swapcase())
print(my_str.lstrip())

In [ ]:
my_str = "1234"
print(my_str.isalpha())
print(my_str.isdigit())
print(my_str.isnumeric())
print(my_str.isalnum())

In [ ]:
my_str = "abcd1234"
print(my_str.isalpha())
print(my_str.isdigit())
print(my_str.isnumeric())
print(my_str.isalnum())

In [ ]:
my_str = "ABCD"
print(my_str.isupper())
print(my_str.islower())

In [ ]:
my_str = "university"
print(my_str.find("vir"))
print(my_str.index("vir"))

In [ ]:
my_str = "university"
print(my_str.startswith("ver"))
print(my_str.startswith("ver",3,6))
print(my_str.startswith("ver",3,10))

In [ ]:
my_str = "university"
print(my_str.endswith("sity"))
print(my_str.endswith("ver",0,6))
print(my_str.endswith("ver",3,10))

In [ ]:
my_str = "@@@@calcutta%%%"
print(my_str,len(my_str))
print(my_str,my_str.lstrip("@"),len(my_str.lstrip("@")))
print(my_str,my_str.rstrip("%"),len(my_str.rstrip("%")))
print(my_str,my_str.strip("@%"),len(my_str.strip("@%")))


In [ ]:
my_str = " "
print(my_str.isspace())
my_str = " abc "
print(my_str.isspace())

In [ ]:
my_str = "Happy New Year 2018"
print(my_str)
print(my_str.replace("2018","2019"))

In [ ]:
my_str = "Wishing You a Happy New Year"
my_list = my_str.split(" ")
print(my_list)
for i in my_list:
    print(i)

In [ ]:
#take a binary no as string as input ...calculate its decimal equivalent


In [ ]:
import math
n = input("Enter binary no:")
l = list(n)
n_len = len(n)
sum = 0 
for i in range(0,n_len):
    sum = sum + int(n[i]) * math.pow(2,len(n)-i-1)
print(sum)



In [ ]:
import math
n = input("Enter binary no:")
l = list(n)
length = len(l)
sum = 0
for i in range(0,length):
    sum = sum + int(l[i]) * math.pow(2,len(l)-i-1)
print(sum)

In [ ]:
s = "sister is good"
l = s.split(" ")
print(l)

In [ ]:
print(" ".join(l))

In [ ]:
#Start of 3rd class...... Bring it on

In [ ]:
## DEALING WITH FUNCTIONS

In [ ]:
def my_addition(num1,num2):
    result = num1 + num2
    print("Performing the addition operation...")
    return(result)
data1 = int(input("Enter the first number:"))
data2 = int(input("Enter the second number"))
print("Sum is",my_addition(data1,data2))
    

In [ ]:
# With single return statement we can return multiple values in python

def my_calculation(data1,data2):
    print("Performing four major calculations...")
    return data1+data2,data1-data2,data1*data2,data1/data2
d1 = int(input("Enter the first number:"))
d2 = int(input("Enter the second number"))
print(my_calculation(d1,d2)) #will return the output in tuples
s,d,p,q=my_calculation(d1,d2)
print(s,d,p,q)



In [ ]:
# Dealing with default arguments...

def my_function(arg1=222,arg2=110,arg3=333):
    print(arg1,arg2,arg3)

my_function(200,100,300)
my_function(200,100)
my_function(200)
my_function()
my_function(arg2=20,arg3=30,arg1=10)
my_function(arg3=30,arg1=10)

In [ ]:
#dealing with default arguments

def my_function(arg1,arg2=None):
    print(arg1)
    if(arg2 is not None):
        print(arg2)
my_function(100,200)
print("-----------------------------------")
my_function(100)


In [26]:
#Dealing with recursion

#Factorial using non-recusrsion
def fact_cal_nr(num):
    fact = 1
    for i in range(1,num+1):
        fact*=i
    return fact

d = int(input("Enter the number:"))
t = fact_cal_nr(d)
print("Factorial of ",d," is ",t)

Enter the number: 5


Factorial of  5  is  120


In [38]:
#Factorial using non-recusrsion

'''def fact_cal_nr(num):
    fact = 2 #loop will run for num-1 no of times
    for i in range(1,num):
        fact*=i
    return fact

d = int(input("Enter the number:"))
t = fact_cal_nr(d)
print("Factorial of ",d," is ",t)'''

Enter the number: 5


Factorial of  5  is  48


In [30]:
#Factorial using recursion

def fact_cal_r(n):
    if n == 0 or  n == 1:
        return 1
    else:
        return n * fact_cal_r(n-1)

print(fact_cal_r(5))


120


In [32]:
def fact_calculation(num,choice):
    if(choice == "r"):
        print("Recursive version executing...")
        print(fact_cal_r(num))
    else:
        print("Non Recursive version executing.....")
        print(fact_cal_nr(num))
fact_calculation(5,"nr")
fact_calculation(5,"r")

Non Recursive version executing.....
120
Recursive version executing...
120


In [34]:
# Lambda function 
# single statement function

sqr_func = lambda x1: x1 * x1
print(sqr_func(4))

16


In [35]:
add_func = lambda a,b: a + b
print(add_func(100,200))

300


In [40]:
outcome = 5 > 4 or 7 > 8
print(outcome)
outcome = 5 > 4 and 7 > 8
print(outcome)
outcome = 5 > 4 and 17 > 8
print(outcome)



True
False
True


In [47]:
a = 250
b = 150
print(a,b,a & b)
print(a,b,a | b)
print(a,b,a ^b)
print(a,~a)

# 250 = 128 + 64 + 32 + 16 + 8 + 2 = 1111 1010
# 150 = 128 + 16 + 4 + 2           = 1001 0110
                               # ----------------- 
#                            And      1001 0010 = 146

#250 = 128 + 64 + 32 + 16 + 8 + 2 =  1111 1010
# 150 = 128 + 16 + 4 + 2          =  1001 0110
                               # ----------------- 
#                            OR    1111 1110 = 254

#250 = 128 + 64 + 32 + 16 + 8 + 2 = 1111 1010
# 150 = 128 + 16 + 4 + 2          = 1001 0110
                               # ----------------- 
#                            XOR    0110 1100 = 108

#250 = 128 + 64 + 32 + 16 + 8 + 2 = 1111 1010
# 1's complement                 =  0000 0101
# 2's complement                 =  0000 0001
#------------------------------------------------------
# ADD                            =  0000 0110


250 150 146
250 150 254
250 150 108
250 -251


In [54]:
#Dealing with list

grocery_list = ["juice","tomatoes","potatoes","bananas"]
print("first item:",grocery_list[0])
print(grocery_list)
print(grocery_list[1:3])
print(grocery_list[-3:3])

first item: juice
['juice', 'tomatoes', 'potatoes', 'bananas']
['tomatoes', 'potatoes']
['tomatoes', 'potatoes']


In [72]:
grocery_list = ["juice","tomatoes","potatoes","bananas"]
other_events = ["car wash","car drive","walk","sleep"]
print(grocery_list)
print(other_events)
print("Using + operator-------")
to_do_list = grocery_list + other_events
print(to_do_list)
print(len(to_do_list))
#print("Using extend keyword---------")
#grocery_list.extend(other_events)
#print(grocery_list)
#print("-----------------------------------")
to_do_list = [grocery_list,other_events]
print(to_do_list)
print(len(to_do_list))
print("----------------------------------------------")
for i in grocery_list:
    print(i)
print("-----------------------------------------------")
print(to_do_list)

print("\n---------------to_do_list---------------------\n")
for i in to_do_list:
    print(i)
    for j in i:
        print(j)


['juice', 'tomatoes', 'potatoes', 'bananas']
['car wash', 'car drive', 'walk', 'sleep']
Using + operator-------
['juice', 'tomatoes', 'potatoes', 'bananas', 'car wash', 'car drive', 'walk', 'sleep']
8
[['juice', 'tomatoes', 'potatoes', 'bananas'], ['car wash', 'car drive', 'walk', 'sleep']]
2
----------------------------------------------
juice
tomatoes
potatoes
bananas
-----------------------------------------------
[['juice', 'tomatoes', 'potatoes', 'bananas'], ['car wash', 'car drive', 'walk', 'sleep']]

---------------to_do_list---------------------

['juice', 'tomatoes', 'potatoes', 'bananas']
juice
tomatoes
potatoes
bananas
['car wash', 'car drive', 'walk', 'sleep']
car wash
car drive
walk
sleep


In [75]:
print(to_do_list[1])
print(to_do_list[1][1:3])

['car wash', 'car drive', 'walk', 'sleep']
['car drive', 'walk']


In [85]:
#list functions

print(grocery_list)
print("\n----------------Appending function----------------------\n")
grocery_list.append("onion")
print(grocery_list)



['juice', 'tomatoes', 'potatoes', 'bananas', 'onion']

----------------Appending function----------------------

['juice', 'tomatoes', 'potatoes', 'bananas', 'onion', 'onion']


In [82]:
print("\n----------------Insert function----------------------\n")
grocery_list.insert(1,"pickle")
print(grocery_list)



----------------Insert function----------------------

['juice', 'pickle', 'tomatoes', 'potatoes', 'bananas', 'onion', 'onion', 'onion']


In [90]:
print("\n----------------Remove function----------------------\n")
#grocery_list.remove("pickle")
grocery_list.remove("onion")
print(grocery_list)


----------------Remove function----------------------

['juice', 'tomatoes', 'potatoes', 'bananas']


In [89]:
my_list1 = ["amit","100","accountant","belgharia"]
print(my_list1)
print("\n---------------Ascending order-----------------\n")
my_list1.sort()
print(my_list1)
print("\n---------------Rerversing----------------------\n")
my_list1.reverse()
print(my_list1)

['amit', '100', 'accountant', 'belgharia']

---------------Ascending order-----------------

['100', 'accountant', 'amit', 'belgharia']

---------------Rerversing----------------------

['belgharia', 'amit', 'accountant', '100']


In [97]:
#REMOVING ITEMS FROM LIST. THERE ARE TWO WAYS:
#1. DELETE 2. REMOVE

my_list1 = ["amit","100","accountant","belgharia"]
my_list1.remove("accountant")
print(my_list1)


['amit', '100', 'belgharia']


In [ ]:
#Using delete function

my_list1 = ["amit","100","accountant","belgharia"]
del my_list1[2]
print(my_list1)

In [101]:
# Dealing with Tuples
# Tuples are immutable and enclosed in {} 
# Enhances data security

my_tuple = (1,2,"amit","male",34)
print(my_tuple)
print(my_tuple[2])
# my_tuple[2] = "amitava" TypeError, cannot be updated because it is immutable

(1, 2, 'amit', 'male', 34)
amit


In [104]:
my_list = list(my_tuple)
my_list[2] = "amitava"
my_tuple = tuple(my_list)
print(my_tuple)

(1, 2, 'amitava', 'male', 34)


In [105]:
my_tuple = (44,22,66,88,55,99)
my_list = [44,22,66,88,55,99]
print(len(my_tuple),max(my_tuple),min(my_tuple))
print(len(my_list),max(my_list),min(my_list))

6 99 22
6 99 22


In [119]:
# Dealing with Dictionaries
#Key-value pairs
diction_fruit = {"banana":"yellow",
                 "apple":"red",
                 "guava":"green",
                 "grape":"black",
                 "orange":"orange"}

In [120]:
print(diction_fruit)

{'banana': 'yellow', 'apple': 'red', 'guava': 'green', 'grape': 'black', 'orange': 'orange'}


In [121]:
print(diction_fruit.keys())

dict_keys(['banana', 'apple', 'guava', 'grape', 'orange'])


In [122]:
print(diction_fruit.values())

dict_values(['yellow', 'red', 'green', 'black', 'orange'])


In [123]:
print(diction_fruit.items())

dict_items([('banana', 'yellow'), ('apple', 'red'), ('guava', 'green'), ('grape', 'black'), ('orange', 'orange')])


In [124]:
my_list = list(diction_fruit)
print(my_list)
my_list = list(diction_fruit.items())
print(my_list)


['banana', 'apple', 'guava', 'grape', 'orange']
[('banana', 'yellow'), ('apple', 'red'), ('guava', 'green'), ('grape', 'black'), ('orange', 'orange')]


In [125]:
print(my_list[2])

('guava', 'green')


In [126]:
print(diction_fruit)
print(diction_fruit["guava"])
print(diction_fruit.get("guava")) #get method
# print(diction_fruit["pineapple"]) key doesnt exist

{'banana': 'yellow', 'apple': 'red', 'guava': 'green', 'grape': 'black', 'orange': 'orange'}
green
green


In [127]:
print(diction_fruit)
diction_fruit["grape"] = "green"
print(diction_fruit)
diction_fruit["mango"] = "yellow"
print(diction_fruit)


{'banana': 'yellow', 'apple': 'red', 'guava': 'green', 'grape': 'black', 'orange': 'orange'}
{'banana': 'yellow', 'apple': 'red', 'guava': 'green', 'grape': 'green', 'orange': 'orange'}
{'banana': 'yellow', 'apple': 'red', 'guava': 'green', 'grape': 'green', 'orange': 'orange', 'mango': 'yellow'}


In [128]:
print(diction_fruit)
del diction_fruit["grape"] #delete that particular key
print(diction_fruit)

{'banana': 'yellow', 'apple': 'red', 'guava': 'green', 'grape': 'green', 'orange': 'orange', 'mango': 'yellow'}
{'banana': 'yellow', 'apple': 'red', 'guava': 'green', 'orange': 'orange', 'mango': 'yellow'}


In [129]:
print(diction_fruit)
diction_fruit.clear()  #clear the entire dictionary
print(diction_fruit)

{'banana': 'yellow', 'apple': 'red', 'guava': 'green', 'orange': 'orange', 'mango': 'yellow'}
{}


In [ ]:
print(diction_fruit)
del diction_fruit  #clear the entire dictionary
print(diction_fruit)

In [138]:
diction_fruit = {"banana":"yellow",
                 "apple":"red",
                 "guava":"green",
                 "grape":"black",
                 "orange":"orange"}
print(diction_fruit)

{'banana': 'yellow', 'apple': 'red', 'guava': 'green', 'grape': 'black', 'orange': 'orange'}


In [139]:
print(diction_fruit["pineapple"])

KeyError: 'pineapple'

In [140]:
try:
    print(diction_fruit["pineapple"])
except KeyError as e:
    print("Error ",e," occured..")

Error  'pineapple'  occured..


In [147]:
#Dealing with sets 
# unordered
# unique values
#creating with empty set
empty_set = set()

#creating a non empty set
languages = {"python","r","java"}
#creating a set from a list
snakes = set (["cobra","viper","python"])
print(languages)
print(snakes)


{'r', 'python', 'java'}
{'cobra', 'viper', 'python'}


In [143]:
len(languages)

3

In [145]:
"python" in languages # set membership operators

True

In [146]:
"cobra" in snakes

True

In [148]:
languages


{'java', 'python', 'r'}

In [149]:
snakes

{'cobra', 'python', 'viper'}

In [159]:
print(languages & snakes)
print(languages.intersection(snakes))

{'python'}
{'python'}


In [158]:
print(languages | snakes)
print(languages.union(snakes))         # \ = union

{'cobra', 'r', 'viper', 'python', 'java'}
{'cobra', 'r', 'viper', 'python', 'java'}


In [166]:
languages.add("sql")
languages.add("r")
print(languages)

{'r', 'sql', 'python', 'java'}


In [167]:
print(languages - snakes)
print(languages.difference(snakes))
print(languages.symmetric_difference(snakes))

{'r', 'sql', 'java'}
{'r', 'sql', 'java'}
{'java', 'cobra', 'r', 'sql', 'viper'}


In [168]:
languages.remove("sql")
print(languages)

{'r', 'python', 'java'}


In [169]:
try:
    languages.remove("c++")
except KeyError as e:
    print("Error ",e)

Error  'c++'


In [170]:
print(languages)

{'r', 'python', 'java'}


In [171]:
languages.remove("c++")

KeyError: 'c++'

In [172]:
languages.add("sql")

In [173]:
languages


{'java', 'python', 'r', 'sql'}

In [176]:
languages.discard("r")  
print(languages)

{'sql', 'python', 'java'}


In [177]:
languages.remove("sql")

In [178]:
print(languages)

{'python', 'java'}


In [181]:
languages.add("r")
languages.add("sql")

In [182]:
print(languages)

{'r', 'sql', 'python', 'java'}


In [183]:
languages.pop()

'r'

In [184]:
languages # r got deleted

{'java', 'python', 'sql'}

In [185]:
languages.clear()
print (languages)

set()


In [186]:
languages.update("122","344")    ******
print(languages)

{'1', '2', '4', '3'}


In [187]:
languages.update("go","spark")

In [188]:
languages

{'1', '2', '3', '4', 'a', 'g', 'k', 'o', 'p', 'r', 's'}

In [190]:
sorted(set([9,0,2,1,0,10,5]))

[0, 1, 2, 5, 9, 10]

In [191]:
my_set = {"amal",80,"rr"}


In [192]:
my_set

{80, 'amal', 'rr'}

In [195]:
l = [80,100,90,45,145,90]
s = set(l)
sorted(s)

[45, 80, 90, 100, 145]

In [1]:
# 3rd class begins

In [2]:
#DEALING WITH OBJECT ORIENTED PROGRAMMING
#DEALING WITH CLASSES AND OBJECTS

In [3]:
# A class have two types of variables
# 1. class variable and 2. instance variables

In [26]:
class My_class:
    __classVar1 = 100
    __classVar2 = 200
    def __init__(self,data1=1,data2=2):         # no constructor overloading and function overloading .. we can implement using default constructor  
        self.__instVar1 = data1
        self.__instVar2 = data2
    def display(self):                                                                                 # no underscore means public section
        print("ClassVar1 = {} and ClassVar2 = {}".format(My_class.__classVar1,My_class.__classVar2))  # dot denotes a membership operator
        print("InstVar1 = {} and InstVar2 = {}".format(self.__instVar1,self.__instVar2)) # Double underscore denotes the member is private section and single underscore means protected section
    def update(self,ndata1,ndata2):
        My_class.__classVar1 = ndata1
        My_class.__classVar2 = ndata2
        

obj1 = My_class(300,400)
obj1.display()
obj1.update(11,22)
obj2 = My_class(500,600)
obj2.display()

ClassVar1 = 100 and ClassVar2 = 200
InstVar1 = 300 and InstVar2 = 400
ClassVar1 = 11 and ClassVar2 = 22
InstVar1 = 500 and InstVar2 = 600


In [34]:
class Animal:
    def __init__(self,name,height,weight,sound):
        self.__name = name
        self.__height = height
        self.__weight = weight
        self.__sound = sound
    def set_name(self,name):           # setter function are required to set the values of the private members of a class 
        self.__name = name
    def set_height(self,height):
        self.__height = height
    def set_weight(self,weight):
        self.__weight = weight
    def set_sound(self,sound):
        self.__sound = sound
    def get_name(self):                 # getter functions are required to get the values set to the variables
        return self.__name
    def get_height(self):
        return self.__height
    def get_weight(self):
        return self.__weight
    def get_sound(self):
        return self.__sound
    def get_type(self):
        print("Animal.....")
    def display(self):
        return "{} is {} cm tall and weight {} and says {}".format(self.__name,self.__height,self.__weight,self.__sound)
        #print("Name"+"  "+"Height" + " " + "Weight" + "Sound")
        #print(self.__name + " " + str(self.__height) + " " + str(self.__weight) + " " + str(self.__sound))

obj = Animal("Lion",175,65,"roar")
print(obj.display())
#obj.display()


Lion is 175 cm tall and weight 65 and says roar


In [41]:
#Dealing With Inheritance
class Dog(Animal):
    def __init__(self,name,height,weight,sound,owner):
        self.__owner = owner
        super(Dog,self).__init__(name,height,weight,sound)        # ***** super keyword is used to call the base class constructor
    def set_owner(self,owner):
        self.__owner = owner
    def get_owner(self):
        return self.__owner
    def multiple_sounds(self,how_many=None):
        if(how_many is None):
            print(self.get_sound())
        else:
            print(self.get_sound() * how_many)
    def get_type(self):
        print("Dog......")  #Just displaying the name of the class and also implementation of function overiding 
    def displayDog(self):
        return "{} is {} cm tall of weight {} and says {} with owner {}".format(self.get_name(),self.get_height(),self.get_weight(),self.get_sound(),self.__owner) #using get function so that we can access the private members of the class which we are inheriting           
spot = Dog("Larry",50,40,"buff","Adam")
print(spot.displayDog())
spot.multiple_sounds(3)                              # Function overloading(Calling function with different no of arguments)
spot.multiple_sounds()


Larry is 50 cm tall of weight 40 and says buff with owner Adam
buffbuffbuff
buff


In [43]:
class Animal_Testing:
    def get_type(self,animal):                                  # passing object but the decision of which class to choose will be decided in run time
        animal.get_type()
test_animals = Animal_Testing()
test_animals.get_type(obj)
test_animals.get_type(spot)
spot.multiple_sounds(3)                             
spot.multiple_sounds()

Animal.....
Dog......
buffbuffbuff
buff


In [92]:
class Tree:
    def __init__(self,tree_code,height,width,amount_spent):
        self.__tree_code = tree_code
        self.__height = height
        self.__width = width
        self.__amount_spent = amount_spent
    def set_tree_code(self,tree_code):
        self.__tree_code = tree_code
    def set_height(self,height):
        self.__height = height
    def set_width(self,width):
        self.__width = width
    def set_amount_spent(self,amount_spent):
        self.__amount_spent = amount_spent
    def get_tree_code(self):
        return self.__tree_code
    def get_height(self):
        return self.__height
    def get_width(self):
        return self.__width 
    def get_amount_spent(self):
        return self.__amount_spent
    def get_type(self):
        print("Tree.............")
    def annual_update(self,htt,wdd,amtt):
        self.__height+= htt
        self.__width+= wdd
        self.__amount_spent+= amtt

    def displayTree(self):
        print("Tree code:",self.__tree_code,"Height:",self.__height,"Width:",self.__width,"Amount_spent:",self.__amount_spent)
    

In [93]:
class MangoTree(Tree):
    def __init__(self,tree_code,height,width,amount_spent,my_yield):
        self.__my_yield = my_yield
        super(MangoTree,self).__init__(tree_code,height,width,amount_spent)
    def set_my_yield(self,my_yield):
        self.__my_yield = my_yield
    def get_my_yield(self):
        return self.__my_yield
    def annual_update(self,htt,wdd,amtt,yyld):
        self.__my_yield+= yyld
        super(MangoTree,self).annual_update(htt,wdd,amtt)
        
    def displayMangoTree(self):
        print("Tree code:",self.get_tree_code(),"Height:",self.get_height(),"Width:",self.get_width(),"Amount_spent:",self.get_amount_spent(),"Yield:",self.__my_yield)
m1 = MangoTree("Man001",200,100,1200,100)
m1.displayMangoTree()
m1.annual_update(100,200,500,700)
m1.displayMangoTree()
        

Tree code: Man001 Height: 200 Width: 100 Amount_spent: 1200 Yield: 100
Tree code: Man001 Height: 300 Width: 300 Amount_spent: 1700 Yield: 800


In [94]:
class Garden:
    def __init__(self,m1,m2,m3,t1,t2):
        self.__mangotree1 = m1
        self.__mangotree2 = m2
        self.__mangotree3 = m3
        self.__tree1 = t1
        self.__tree2 = t2
    def total_yield(self):
        return(self.__mangotree1.get_my_yield() +  self.__mangotree2.get_my_yield() + self.__mangotree3.get_my_yield())
    def total_spent(self):
        return(self.__mangotree1.get_amount_spent()+self.__mangotree2.get_amount_spent()+self.__mangotree3.get_amount_spent()+self.__tree1.get_amount_spent()+self.__tree2.get_amount_spent())
    def gardendisplay(self):
        print("Displaying all trees............................")
        self.__mangotree1.displayMangoTree()
        self.__mangotree2.displayMangoTree()
        self.__mangotree3.displayMangoTree()
        self.__tree1.displayTree()
        self.__tree2.displayTree()
        print("Total Amount spent",self.total_spent())
        print("Total Amount yield",self.total_yield())
        
ma1 = MangoTree("Himsagar",20,8,1200,1000)
ma2 = MangoTree("Chausa",21,9,1400,1200)
ma3 = MangoTree("Langra",22,10,1600,1400)
tre1 = Tree("Banyan",10,6,1200)
tre2 = Tree("Palm",11,6,1400) 
g1=Garden(ma1,ma2,ma3,tre1,tre2)
print(g1.gardendisplay())
#print("Total Amount spent:",g1.total_spent())
#print("Total Amount spent:",g1.total_yield())


Displaying all trees............................
Tree code: Himsagar Height: 20 Width: 8 Amount_spent: 1200 Yield: 1000
Tree code: Chausa Height: 21 Width: 9 Amount_spent: 1400 Yield: 1200
Tree code: Langra Height: 22 Width: 10 Amount_spent: 1600 Yield: 1400
Tree code: Banyan Height: 10 Width: 6 Amount_spent: 1200
Tree code: Palm Height: 11 Width: 6 Amount_spent: 1400
Total Amount spent 6800
Total Amount yield 3600
None


In [9]:
#DEALING WITH NUMPY.........
#importing Numpy module......
import numpy as np


In [10]:
#creating nd-array from the lists
#note that,every element must be the same type(will be converted if possible) 
data1 = [1,2,3,4,5] #defining a list
print(data1)            #displaying the list
arr1 = np.array(data1)  #creating 1-d array
print(arr1)             #dipslaying the array
# numpy used in data manipulation and numpy contains items of same data type only and not diff data type as in lists

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [17]:
data2 = [range(1,5),range(5,9)]   # list of lists
print(data2)                      #display
arr2 = np.array(data2)            #2d array , you can create n no of arrays 
print(arr2)
my_list = arr2.tolist()           # converting array back to list
print(my_list)

[range(1, 5), range(5, 9)]
[[1 2 3 4]
 [5 6 7 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [14]:
my_list = [11,22,33,44,55]
print(my_list)
arr3 = np.array(my_list)
print(arr3)

[11, 22, 33, 44, 55]
[11 22 33 44 55]


In [26]:
#examining the array
print(arr1)
print(arr2)
print(arr1.dtype) # returns the data type
print(arr2.dtype)
print(arr1.ndim) # returns no of dimensions
print(arr2.ndim)
print(arr1.shape)  # singleton therefore display only no. of items
print(arr2.shape)  # [2,4] axis-0 rows, axis-1 cols
print("------------------------")
print(arr1.size)   # total no of elements
print(arr2.size)
print("------------------------")
print(len(arr1))  # returns no of rows
print(len(arr2))
print(len(arr2[0]))

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
int32
int32
1
2
(5,)
(2, 4)
------------------------
5
8
------------------------
5
2
4


In [47]:
# Creating special type of arrays
print(np.zeros(10))    # array with 10 float64 zero values
print(np.zeros((3,6))) # 2-d array filled with 0's 
print(np.ones(10))     # array with 10 float64 one values and single precision floating point no is 32 bits and double precision floating point no is 64 bits
print(np.ones(10).dtype)
print(np.ones((3,6)))   # taking using (3,6) as tuples
m = np.ones(10)
m = m.reshape(10)
print(m)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [43]:
print ( np.linspace(0,1,5)) # 0 to 1(inclusive) with 5 points
print ( np.logspace(0,3,4)) # 10^0 to 10^3 (inclusive) with 4 points i.e starting from 0 to 3 with 4 equidistant points

[0.   0.25 0.5  0.75 1.  ]
[   1.   10.  100. 1000.]


In [45]:
# arange is like range, except it returns an array (not a list)
int_array = np.arange(5)            # arange here means array's range
print(int_array)
float_array = int_array.astype(float) # converting int array to float
print(float_array)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]


In [75]:
matrix = np.arange(10,dtype=float)
print(matrix)
print(matrix.T)
print(matrix[:,np.newaxis])
print(matrix[:,np.newaxis].T)
#print(matrix.T)
matrix = matrix.reshape(5,2)   # conversion from one dimensional array to 2d array
print(matrix)
matrix = matrix.reshape(2,5)
print(matrix)
matrix = matrix.flatten(5)
print(matrix)
#print(matrix.T)      # transpose of n d array , one dimensional cant be transposed , transpose is done on 2-d array
#matrix = matrix.reshape(2,6) # error because 2*6=12 != 10 hence it will  not work

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]
 [7.]
 [8.]
 [9.]]
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[0. 5. 1. 6. 2. 7. 3. 8. 4. 9.]


G:\Anaconda\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  # This is added back by InteractiveShellApp.init_path()


In [53]:
#adding an axis
a = np.array([0,1])
print(a)
a_col = a[:,np.newaxis]
print(a_col)

[0 1]
[[0]
 [1]]


In [60]:
# stack arrays
# stack flat arrays in columns
# selection: single item
data1 = [1,2,3,4,5]    #defining a list
print(data1)           # displaying the list
arr1 = np.array(data1) # creating 1-d array
print(arr1)            # displaying the array
print(arr1[0])         # 0th element,slices like a list
print(arr2)
print(arr2[0,3])       # data at row no. 0 and col no. 3
print(arr2[0][3])      # alternative syntax

[1, 2, 3, 4, 5]
[1 2 3 4 5]
1
[[1 2 3 4]
 [5 6 7 8]]
4
4


In [66]:
#nd -array slicing
print(arr2)    #displaying
print("-----------------------------------")
print(arr2[0,:]) # full row 0 content
print("-----------------------------------")
print(arr2[:,0]) # full column 0 content
print("-----------------------------------")
print(arr2[:, :2]) #columns strictly before index 2
print("-----------------------------------")
print(arr2[:,2:])  #columns after index 2 inclusive
print("-----------------------------------")
print(arr2[:,1:4]) #columns between 1(inclusive) and 4(exclusive)
print("-----------------------------------")
print(arr2[1][1:3])

[[1 2 3 4]
 [5 6 7 8]]
-----------------------------------
[1 2 3 4]
-----------------------------------
[1 5]
-----------------------------------
[[1 2]
 [5 6]]
-----------------------------------
[[3 4]
 [7 8]]
-----------------------------------
[[2 3 4]
 [6 7 8]]
-----------------------------------
[6 7]


In [69]:
# views and copies 
arr = np.arange(10)
print(arr)
print(arr[5:8])
arr[5:8] = 12 # array is mutable.
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [72]:
arr = np.arange(10)
print(arr)
arr_view = arr[5:8]    # creating a view of the array and not creating a copy
print(arr_view)
arr_view[:] = 13        # upadating arr_view not arr
print(arr_view)
print(arr)              # but modifies both arr,arr_view

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[13 13 13]
[ 0  1  2  3  4 13 13 13  8  9]


In [74]:
arr = np.arange(10)
print(arr)
arr_copy = arr[5:8].copy() # creating a copy of the array not creating a view
print(arr_copy)
arr_copy[:] = 13        #updating both arr_copy not arr
print(arr_copy)
print(arr)               #modifies only arr_copy not arr

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[13 13 13]
[0 1 2 3 4 5 6 7 8 9]


In [77]:
#using boolean arrays
print(arr)
print(arr[arr>5])   #those values will get selected who will satisfy the condition given

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [78]:
#boolean selection return a view which authorizes the modification of the original array
print(arr)
arr[arr>5] = 0
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 0 0 0 0]


In [85]:
names = np.array(['bob','Joe','Will','bob'])
print(names == 'bob')
print(names[names != 'bob'])
print(names[(names == 'bob') | (names ==  'Will')]) # keywords and,or will work here for nd-array
print(names)
names[names != 'bob'] = "pat"
print(names)

[ True False False  True]
['Joe' 'Will']
['bob' 'Will' 'bob']
['bob' 'Joe' 'Will' 'bob']
['bob' 'pat' 'pat' 'bob']


In [90]:
names = np.array(['bob','Joe','Will','bob'])
print(names)
print(names[2])
names = names[names != names[2]]
print(names)
print(np.unique(names))

['bob' 'Joe' 'Will' 'bob']
Will
['bob' 'Joe' 'bob']
['Joe' 'bob']


In [106]:
# vectorized operations.......
nums = np.arange(5)
print(nums)
print(nums * 10)
nums_result = nums ** 2
print(nums_result)
nums_result = np.sqrt(nums)
print(nums_result)
nums_result = np.ceil(nums)
print(nums_result)
nums_result = np.floor(nums)
print(nums_result)
nums_result = np.isnan(nums)  #isnan=> is not-a-number
print(nums_result)
values = np.array([10,40,50,400])
print(np.isnan(values))

[0 1 2 3 4]
[ 0 10 20 30 40]
[ 0  1  4  9 16]
[0.         1.         1.41421356 1.73205081 2.        ]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[False False False False False]
[False False False False]


In [118]:
print(nums)
print(np.array([1,-2,3,-4,15]))
print(nums + np.array([1,2,3,-4,5]))
print("--------------------Maximum--------------------------")
print(np.maximum(nums,np.array([1,-2,3,-4,15])))
print("---------------------Minimum------------------------")
print(np.minimum(nums,np.array([1,-2,3,-4,15])))

[0 1 2 3 4]
[ 1 -2  3 -4 15]
[ 1  3  5 -1  9]
--------------------Maximum--------------------------
[ 1  1  3  3 15]
---------------------Minimum------------------------
[ 0 -2  2 -4  4]


In [127]:
# calculating the euclidean distance between 2 vectors
vect1 = np.random.randn(10)                              #X=(x1,x2,x3.....x10)
vect2 = np.random.randn(10)                              #Y=(y1,y2,........y10)
dist = np.sqrt(np.sum((vect1 - vect2) ** 2))             # d = sqrt(sqr(x1-y1)+................)
print(vect1)                                             # here randn signifies it can generate both +ve and -ve numbers but rand produces only +ve values 
print(vect2)
print("Dist=",dist)

[-1.0619065  -1.69454958  0.97336594 -1.30945045 -1.15910324 -0.28757084
  1.76071845 -0.15371758 -0.02860223  3.61886338]
[ 0.92438907 -0.3687256  -1.62597591  0.5811196  -1.97263702  0.38961368
 -0.60412874  0.87193858 -0.44670526  1.27788393]
Dist= 5.427144395004767


In [130]:
np.random.seed(112233)            #seed is used to stop the further changing of random value after its first operation
print(np.random.randn(5))
print(np.random.rand(5))
                                     


[ 1.46565154  0.46533981 -0.8995737  -1.06731279 -0.12397286]
[0.77770528 0.93577378 0.11326568 0.79567485 0.34407403]


In [139]:
np.random.seed(112234)
print(np.random.randn(2,3))
print(np.random.rand(2,3))
# from 0 to 1 then np.random.rand(50)
# from 0 to 25 then np.random.rand(50)*25
# from 15 to 40 then np.random.rand(50)*25 + 15
# from -10 to 10 then np.random.rand(50)*20 -10
# general formula np.random.rand(no of numbers)*diff + starting number


[[ 0.05749502 -0.34726897 -0.23954989]
 [-0.57023485 -0.73068927 -1.47943432]]
[[0.24622755 0.67822135 0.28753812]
 [0.4607131  0.18944622 0.21156792]]


In [141]:
print(np.random.randint(0,4,10))    # generate only integer numbers between 0 and (4-1)=3
print(np.random.randint(0,2,10))

[0 2 0 2 0 3 1 2 0 2]
[1 1 1 0 1 0 1 0 1 1]


In [144]:
# maths and stats
rnd = np.random.randn(4,2) #random no. in 4*2 array
print(rnd)
print(rnd.mean())
print(rnd.std())      #calculating standard deviation
print(rnd.argmin())   #index of minimum element
print(rnd.sum())
print(rnd.sum(axis = 0))  #sum of columns
print(rnd.sum(axis = 1))  #sum of rows

[[-0.6502671   0.9563455 ]
 [-0.38256615 -1.82617421]
 [-1.49461813 -0.51433324]
 [-0.86974803  0.98083849]]
-0.47506535910670844
0.9506671467157618
3
-3.8005228728536675
[-3.39719941 -0.40332346]
[ 0.3060784  -2.20874036 -2.00895137  0.11109046]


In [147]:
#methods for boolean arrays
print(rnd)
print((rnd > 0 ).sum()) # counts no of posistive values
print((rnd > 0 ).any()) #checks is any value is true
print((rnd > 0).all()) #checks is all values are true

[[-0.6502671   0.9563455 ]
 [-0.38256615 -1.82617421]
 [-1.49461813 -0.51433324]
 [-0.86974803  0.98083849]]
2
True
False


In [148]:
# reshape, transpose and flatten
nums = np.arange(32).reshape(8,4) #creates 8*4 array
print(nums)
print(nums.T)               #transpose
print(nums.flatten())       #flatten

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [149]:
#broadcasting

a = np.array(([0 , 0 , 0],
              [10,10,10],[20,20,20],[30,30,30]))
b = np.array([0,1,2])
print(a)
print(b)
print(a+b)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [153]:
#broadcasting

a = np.array([[0],[10],[20],[30]])
b = np.array([0,1,2])
print(a)
print(b)
print(a+b)

[[ 0]
 [10]
 [20]
 [30]]
[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [166]:
# given the array:
x = np.random.randn(4,2) #random numbers in 4*2 array
# for each column find the row index of the min value
print(x)
print(x[0:4,0].argmin())
print(x[0:4,1].argmin())


[[-0.69438963  1.14759625]
 [ 0.03353754  0.1268967 ]
 [ 0.14315549 -0.05902898]
 [-1.52265777 -0.43269489]]
3
3
